window.__SHOP_ENV__ = {
  NEXT_PUBLIC_SUPABASE_URL: "https://qhlxjjtjidpfgavwhmvr.supabase.co",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFobHhqanRqaWRwZmdhdndobXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MjYzMzAsImV4cCI6MjA5MDMwMjMzMH0.exsizmbcPgYRqyb_vtmhzsbaVOcEVhXP0BqmToSbWQo",
  NEXT_PUBLIC_ADMIN_PHONE: "+250792866248",
  NEXT_PUBLIC_WHATSAPP_PHONE: "+250784141575",
  BUSINESS_NAME: "RUGERO Agro-Daily Ltd Online Shop"
};
